### PR TITLE
Fix continue possibly closing too many upvalues

### LINKED ISSUE #796: Continue closing too many upvalues
I just noticed that the patch https://github.com/PlutoLang/Pluto/pull/779 closes to many upvalues as can be seen in the following example where no upvalues should be closed by the continue statement.

```lua
local function test(w, r)
    w(1)
    assert(r()==1)
    return true
end

repeat
    local val
    local function write(v) val = v end
    continue
until test(write, ||->val)
```

### PR DESCRIPTION
**Pull request by Sainan**

### CODE REVIEW

File: src/lparser.cpp [hunk 1]
```diff
@@ -1314,22 +1314,36 @@ static void continuestat (LexState *ls) {
...
     }
+    else {  /* not a loop, continue search */
+      bl = bl->previous;
+    }
   }
   if (bl) {
-    luaK_codeABC(fs, OP_CLOSE, bl->nactvar, 0, 0); /* close upvalues */
-    luaK_concat(fs, &bl->scopeend, luaK_jump(fs));
+    if (bl->nactvarbeforecontinue != -1) {  /* repeat...until? */
+      luaK_concat(fs, &bl->breaklist, luaK_jump(fs));
```
Comment (XmiliaH) [inline src/lparser.cpp]: Why put `continue`s on the breaklist?

Comment (Sainan) [reply src/lparser.cpp]: So it can reuse the OP_CLOSE that repeatstat already generates.

Comment (XmiliaH) [reply src/lparser.cpp]: But now
```lua
repeat
  break
until false
```
is the same as
```lua
repeat
  continue
until false
```
since `continue` and `break` both land on the `breaklist`

Comment (Sainan) [reply src/lparser.cpp]: It's not, because continue lands on `bl2.breaklist` and break lands on `bl1.breaklist`.

Comment (XmiliaH) [reply src/lparser.cpp]: But something is still wrong since
```lua
repeat
    continue
until false
```
should loop forever but exits. Also the bytecode is:
```
0+ params, 2 slots, 1 upvalue, 0 locals, 0 constants, 0 functions
        1       [-]     VARARGPREP      0
        2       [2]     JMP             3       ; to 6
        3       [3]     LOADFALSE       0
        4       [3]     TEST            0 0
        5       [3]     JMP             0       ; to 6
        6       [3]     RETURN          0 1 1   ; 0 out
```
and the JMP at 2 is not jumping to 3 but 6.

**Comment by XmiliaH** [comment]
Not the close is missing again
```lua
local t
repeat
    do
        local u1, u2, u3, u4
        t = ||->u4
        continue
    end
until true
do
    for k in pairs({}) do end
end
print(t())
```

**Comment by XmiliaH** [comment]
The new function should also be used for `for`-loops
```lua
local t
do
    for i = 1, 1 do
        do
            local u1
            t = ||->u1
            continue
        end
    end
end
do
    local x
    for k in pairs({}) do end
end
print(t())
```
